# NOTE: aws ecs cli tool only supports version 1 docker-compose file format
db:
    image: postgres
rabbitmq:
    image: rabbitmq
redis:
    image: redis
nginx:
    restart: always
    image: naphatkrit/tigerhost-nginx
    ports:
        - "80:80"
    links:
        - web:web
web:
    restart: always
    image: naphatkrit/tigerhost-main
    command: bin/web.sh
    environment:
        DATABASE_URL: postgres://postgres@db:5432/postgres
        BROKER_URL: amqp://guest:guest@rabbitmq:5672//
        CELERY_RESULT_BACKEND: redis://redis:6379/
    expose:
        - "8000"
    links:
        - db:db
        - redis:redis
        - rabbitmq:rabbitmq
worker:
    image: naphatkrit/tigerhost-main
    command: bin/worker.sh
    environment:
        DATABASE_URL: postgres://postgres@db:5432/postgres
        BROKER_URL: amqp://guest:guest@rabbitmq:5672//
        CELERY_RESULT_BACKEND: redis://redis:6379/
    links:
        - db:db
        - redis:redis
        - rabbitmq:rabbitmq
