version: '2'
services:
    addon1:
        environment:
            POSTGRES_USER: "addon1"
        image: postgres
    addon2:
        environment:
            POSTGRES_USER: "addon2"
        image: postgres
    proxy:
        build: .
        command: proxy
        ports:
            - "5432:5432"
