version: '2'
services:
    db:
        image: postgres
    rabbitmq:
        image: rabbitmq
    redis:
        image: redis
    web:
        build: .
        command: bin/run_web.dev.sh
        environment:
            DATABASE_URL: postgres://postgres@db:5432/postgres
            BROKER_URL: amqp://guest:guest@rabbitmq:5672//
            CELERY_RESULT_BACKEND: redis://redis:6379/
        volumes:
            - .:/code
        ports:
            - "80:8000"
        depends_on:
            - db
            - rabbitmq
            - redis
    worker:
        build: .
        command: bin/worker.sh
        environment:
            DATABASE_URL: postgres://postgres@db:5432/postgres
            BROKER_URL: amqp://guest:guest@rabbitmq:5672//
            CELERY_RESULT_BACKEND: redis://redis:6379/
        volumes:
            - .:/code
        depends_on:
            - db
            - rabbitmq
            - redis
