version: '2'
services:
    db:
        image: postgres
        ports:
            - "5432:5432"
    rabbitmq:
        image: rabbitmq
        ports:
            - "5672:5672"
    redis:
        image: redis
        ports:
            - "6379:6379"
